<?php


class Inchoo_Tickets_Adminhtml_Block_Ticket_View_Tab_Messages extends Mage_Adminhtml_Block_Template
    implements Mage_Adminhtml_Block_Widget_Tab_Interface
{
    protected function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub
    }

    public function getTicket()
    {
        return Mage::registry('current_ticket');
    }

    public function getTabLabel()
    {
        return Mage::helper('inchoo_tickets')->__('Messages');
    }

    public function getTabTitle()
    {
        return Mage::helper('inchoo_tickets')->__('Ticket Messages');
    }

    public function getTabClass()
    {
        return 'ajax only';
    }

    public function getClass()
    {
        return $this->getTabClass();
    }

    public function getTabUrl()
    {
        return $this->getUrl('*/*/messages', array('_current' => true));
    }

    public function canShowTab()
    {
        return true;
    }

    public function isHidden()
    {
        return false;
    }
}