<div class="page-title">
    <h1>Submit New Ticket</h1>
</div>
<?php //echo $this->getMessagesBlock()->toHtml() ?>
<form action="<?php echo $this->getFormSaveTicketUrl() ?>" method="post" id="form-validate">
    <div class="fieldset">
        <?php echo $this->getBlockHtml('formkey')?>
        <input type="hidden" name="success_url" value="<?php //echo $this->getSuccessUrl() ?>" />
        <input type="hidden" name="error_url" value="<?php //echo $this->getErrorUrl() ?>" />
        <h2 class="legend"><?php echo $this->__('Ticket') ?></h2>
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <ul class="form-list">
            <li class="fields">
                <label for="subject" class="required"><?php echo $this->__('Subject') ?></label>
                <div class="input-box">
                    <input type="text" name="subject" id="subject" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Subject')) ?>" class="input-text required-entry"  />
                </div>
                <label for="message" class="required"><?php echo $this->__('Message') ?></label>
                <div class="input-box">
                    <textarea id="message_text" class="required-entry validate-length maximum-length-256" name="message" rows="5" cols="25" ></textarea>
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="back-link"><a href="<?php //echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button data-action="save-customer-address" type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Submit Ticket')) ?>" class="button"><span><span><?php echo $this->__('Submit Ticket') ?></span></span></button>
    </div>
</form>
