
<?php /** @var $this Inchoo_Tickets_Block_Tickets */ ?>
<?php $_ticket = $this->getTicket() ?>
<?php $_messages = $this->getMessages(); ?>
<?php echo $this->getMessagesBlock()->toHtml() ?>
<div class="page-title title-buttons">
    <h1><?php echo $this->__('Ticket #%s - %s', $_ticket->getTicketId(), $_ticket->getStatus() ? 'Opened' : 'Closed') ?></h1>
    <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Reply')) ?>" class="button" onclick="window.location='<?php echo $this->getNewMessageUrl() ?>';"><span><span><?php echo $this->__('Reply') ?></span></span></button>
</div>
<dl class="order-info">
    <dt><?php echo $this->__('About This Ticket:') ?></dt>
    <dd>
        <ul id="order-info-tabs">
            <li class="current">Ticket Information</li>
        </ul>
<!--        <script type="text/javascript">decorateGeneric($('order-info-tabs').select('LI'),['first','last']);</script>-->
    </dd>
</dl>
<p class="order-date"><?php echo $this->__('Date Created: %s', $this->formatDate($_ticket->getCreatedAt(), 'medium', true)) ?></p>
<div class="">
    <div class="box">
        <h2><?php echo $_ticket->getSubject(); ?></h2>
    </div>
    <div class="box-content">
        <address><?php echo $_ticket->getMessage(); ?></address>
    </div>
</div>
<div>
    <?php foreach($_messages as $_message): ?>
        <div>
            <p><?php echo $_message->getMessage(); ?></p>
        </div>
    <?php endforeach ?>
</div>

