<?php $_ticket = $this->getTicket() ?>
<div class="box-left">
    <!--Account Information-->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4><?php echo Mage::helper('inchoo_tickets')->__('Ticket Information') ?></h4>
        </div>
        <div class="fieldset">
            <div class="hor-scroll">
                <table cellspacing="0" class="form-list">
                    <tr>
                        <td class="label"><label><?php echo Mage::helper('inchoo_tickets')->__('Customer Name') ?></label></td>
                        <td class="value"><strong><?php echo $this->escapeHtml($this->getCustomer()) ?></strong></td>
                    </tr>
                    <tr>
                        <td class="label"><label><?php echo Mage::helper('inchoo_tickets')->__('Status') ?></label></td>
                        <td class="value"><strong><?php echo $_ticket->getStatus() ? 'Opened' : 'Closed' ?></strong></td>
                    </tr>
                    <tr>
                        <td class="label"><label><?php echo Mage::helper('inchoo_tickets')->__('Date Created') ?></label></td>
                        <td class="value"><strong><?php echo $this->formatDate($_ticket->getCreatedAt(), 'medium', true) ?></strong></td>
                    </tr>
                    <?php if (!$_ticket->getStatus()): ?>
                    <tr>
                        <td class="label"><label><?php echo Mage::helper('inchoo_tickets')->__('Date Closed') ?></label></td>
                        <td class="value"><strong><?php echo $this->formatDate($_ticket->getClosedAt(), 'medium', true) ?></strong></td>
                    </tr>
                    <?php endif; ?>

                </table>
            </div>
        </div>
    </div>
</div>