<div class="page-title">
    <h1>Reply to ticket</h1>
</div>
<?php echo $this->getMessagesBlock()->toHtml() ?>
<form action="<?php echo $this->getFormSaveMessageUrl() ?>" method="post" id="message-form">
    <div class="fieldset">
        <?php echo $this->getBlockHtml('formkey') ?>
        <input type="hidden" name="success_url" value="<?php //echo $this->getSuccessUrl() ?>"/>
        <input type="hidden" name="error_url" value="<?php //echo $this->getErrorUrl() ?>"/>
        <h2 class="legend"><?php echo $this->__('Message') ?></h2>
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <ul class="form-list">
            <li>
                <label for="message" class="required"><?php echo $this->__('Message') ?></label>
                <div class="input-box">
                    <textarea id="message_text" class="required-entry" name="message" rows="5" cols="8"></textarea>
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackToTicketUrl()) ?>">
                <small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button data-action="save-customer-message" type="submit"
                title="<?php echo Mage::helper('core')->quoteEscape($this->__('Submit Message')) ?>" class="button">
            <span><span><?php echo $this->__('Submit Message') ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
    //<![CDATA[
    var dataForm = new VarienForm('message-form', true);
    //]]>
</script>